# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-07-25 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_order_ordergoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_address', models.CharField(max_length=128)),
                ('a_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AXFUser')),
            ],
            options={
                'db_table': 'axf_address',
            },
        ),
    ]
