# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-08-01 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='a_phone',
            field=models.CharField(default=123, max_length=32),
        ),
    ]
