ALL_TYPE="0"

#order
ORDER_TOTAL="0"
ORDER_PRICE_UP="1" #价格升序
ORDER_PRICE_DOWN="2" #价格降序
ORDER_SALE_UP="3"
ORDER_SALE_DOWN="4"

#order status
#已下单未付款
ORDER_STATUS_NO_PAY=1
#已下单已付款未发货
ORDER_STATUS_NO_SEND=2
#已下单已付款已发货未收货
ORDER_STATUS_NO_RECEIVE=3
#已下单已付款已收货-待评价
ORDER_STATUS_NO_COMMENT=4

#register
HTTP_OK=200
HTTP_USER_EXIST=901
HTTP_EMAIL_EXIST=901
PASSWORD_NOT_MATCH=801

#login
NOT_LOGIN=601
HTTP_USERINFO_ERROR=701